# Generated by Django 3.2 on 2024-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_vacancies_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='department_az',
            field=models.CharField(choices=[('Product Development and Research', 'Product Development and Research'), ('Marketing and Branding', 'Marketing and Branding'), ('Sales and Distribution', 'Sales and Distribution'), ('Finance and Administration', 'Finance and Administration'), ('Research and Analytics', 'Research and Analytics'), ('Creative and Design', 'Creative and Design')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='department_en',
            field=models.CharField(choices=[('Product Development and Research', 'Product Development and Research'), ('Marketing and Branding', 'Marketing and Branding'), ('Sales and Distribution', 'Sales and Distribution'), ('Finance and Administration', 'Finance and Administration'), ('Research and Analytics', 'Research and Analytics'), ('Creative and Design', 'Creative and Design')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='jobtitle_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='jobtitle_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='location_az',
            field=models.CharField(choices=[('BAKU', 'BAKU'), ('SYDNEY', 'SYDNEY'), ('ZURICH', 'ZURICH'), ('TOKYO', 'TOKYO'), ('SAN-FRANCISCO', 'SAN-FRANCISCO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='location_en',
            field=models.CharField(choices=[('BAKU', 'BAKU'), ('SYDNEY', 'SYDNEY'), ('ZURICH', 'ZURICH'), ('TOKYO', 'TOKYO'), ('SAN-FRANCISCO', 'SAN-FRANCISCO')], max_length=50, null=True),
        ),
    ]
