# Generated by Django 3.2 on 2024-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20240218_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='subject_az',
            field=models.CharField(choices=[('GENERAL INQUIRY', 'GENERAL INQUIRY'), ('CUSTOMER SUPPORT', 'CUSTOMER SUPPORT'), ('FEEDBACK OR SUGGESTIONS', 'FEEDBACK OR SUGGESTIONS'), ('PARTNERSHIP OR COLLABORATIONS', 'PARTNERSHIP OR COLLABORATIONS')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject_en',
            field=models.CharField(choices=[('GENERAL INQUIRY', 'GENERAL INQUIRY'), ('CUSTOMER SUPPORT', 'CUSTOMER SUPPORT'), ('FEEDBACK OR SUGGESTIONS', 'FEEDBACK OR SUGGESTIONS'), ('PARTNERSHIP OR COLLABORATIONS', 'PARTNERSHIP OR COLLABORATIONS')], max_length=30, null=True),
        ),
    ]
