# Generated by Django 3.2 on 2023-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_delete_skintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('ACNE', 'ACNE'), ('NORMAL', 'NORMAL'), ('DRY', 'DRY')], max_length=300, null=True),
        ),
    ]
