# Generated by Django 3.2 on 2023-12-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
