# Generated by Django 3.2 on 2024-02-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productrating_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_az',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_az',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('ACNE', 'ACNE'), ('NORMAL', 'NORMAL'), ('DRY', 'DRY')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_en',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('ACNE', 'ACNE'), ('NORMAL', 'NORMAL'), ('DRY', 'DRY')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_az',
            field=models.CharField(blank=True, choices=[('NEW IN', 'NEW IN'), ('LOW STOCK', 'LOW STOCK')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_en',
            field=models.CharField(blank=True, choices=[('NEW IN', 'NEW IN'), ('LOW STOCK', 'LOW STOCK')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
