# Generated by Django 3.2 on 2024-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20240212_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
