# Generated by Django 3.2 on 2024-02-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20240212_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
    ]
