# Generated by Django 3.2 on 2024-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20240212_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_en',
        ),
    ]
