# Generated by Django 3.2 on 2024-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20240212_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skin_az',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('ACNE', 'ACNE'), ('NORMAL', 'NORMAL'), ('DRY', 'DRY')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_en',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('SENSITIVE', 'SENSITIVE'), ('OILY', 'OILY'), ('ACNE', 'ACNE'), ('NORMAL', 'NORMAL'), ('DRY', 'DRY')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_az',
            field=models.CharField(blank=True, choices=[('NEW IN', 'NEW IN'), ('LOW STOCK', 'LOW STOCK')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_en',
            field=models.CharField(blank=True, choices=[('NEW IN', 'NEW IN'), ('LOW STOCK', 'LOW STOCK')], max_length=300, null=True),
        ),
    ]
