# Generated by Django 3.2 on 2024-02-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20240212_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
    ]
