# Generated by Django 3.2 on 2024-02-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20240214_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skin_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_en',
        ),
    ]
